import "./globals.css";
import "material-icons/iconfont/material-icons.css";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import Header from "./components/Header";

const nunito = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Rest Countries",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={nunito.className}>
                <Header />
                {children}
            </body>
        </html>
    );
}
